### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by beew** [OpenMx/OpenMx#360]
I tried to install openmx with the script 

source('https://vipbg.vcu.edu/vipbg/OpenMx2/software/getOpenMx.R')

After building for a long time, it failed with

```
MarkovExpectation.o MarkovFF.o asa.o asubnp.o ba81quad.o dmvnorm.o fitMultigroup.o general.o glue.o matlogexp.o matrix.o mvbvn.o nanotimer.o omxAlgebra.o omxAlgebraFitFunction.o omxData.o omxExpectation.o omxExpectationBA81.o omxExportBackendState.o omxFIMLFitFunction.o omxFitFunction.o omxFitFunctionBA81.o omxGREMLExpectation.o omxGREMLfitfunction.o omxHessianCalculation.o omxImportFrontendState.o omxLISRELExpectation.o omxMLFitFunction.o omxMatrix.o omxNLopt.o omxNPSOLSpecific.o omxNormalExpectation.o omxRAMExpectation.o omxRFitFunction.o omxRowFitFunction.o omxState.o omxStateSpaceExpectation.o omxSymbolTable.o omxWLSFitFunction.o optimize.o options.o penalty.o povRAM.o sadmvn.o slsqp.o ssMLFit.o stop.o -fopenmp -L../src -lnpsol -llapack -lblas -lgfortran -lm -lquadmath -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
../src/libnpsol.a: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: OpenMx.so] Error 1
ERROR: compilation failed for package ‘OpenMx’
* removing ‘/usr/lib/R/library/OpenMx’
```

R 4.2.2, OS is Ubuntu 22.04, tried build with gcc 11.3 as well as gcc9

**Comment by RMKirkpatrick** [comment]
I just committed dab591c.  It won't fix your issue with the getOpenMx.R script, but you should now be able to build OpenMx from a clone of the OpenMx git repository.  You'd be building from the master branch.  Are you willing/able to do that?  I can provide some guidance if so.

Also, which specific version of gcc9 did you try?

**Comment by beew** [comment]
Hi, 

Yes, I can try that if you give me the instructions. It is gcc-9.5.0

**Comment by RMKirkpatrick** [comment]
For anyone reading this issue, I plan to soon post instructions to the OpenMx website on how to build OpenMx from its source repository under Linux/GNU.  When I do, I will link to those instructions in this issue thread.

**Comment by tbates** [comment]
Be good to have those: I updated the macOS instructions to current practice which is much smoother than it used to be for clang fortran and openMP.
Or if the straight Linux instructions are good, this could be closed.

https://openmx.ssri.psu.edu/wiki/howto-build-openmx-source-repository#OSX

**Comment by RMKirkpatrick** [comment]
OK, I will try to update the instructions for Linux as soon as I can.
